spring:
  profiles:
    group:
      local:
        - common
        - local
        - env
      test:
        - local
        - test
      stg:
        - common
        - stg
      prod:
        - common
        - prod